# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target ‘NisitKUSRC’ do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!
pod 'Alamofire', '~> 3.4’
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MBProgressHUD', '~> 0.9.2'
pod ’IQKeyboardManagerSwift'
pod 'SDWebImage', '~>3.8'
pod 'ObjectMapper', '~> 1.3'
end

