# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.0’

target ‘PersonalTester’ do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

pod 'ObjectMapper', '~> 1.3'
end

